version: "3.3"

services:
  api:
    container_name: api
    image: lspiridonov/smartserver-smart:latest
    ports:
      - "9888:8080"
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    networks:
      - internal_net

  rasp:
    container_name: rasp
    build: .
    restart: unless-stopped
    devices:
      - /dev/gpiomem
    depends_on:
      - api
    networks:
      - internal_net

  db:
    container_name: db
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db_vol:/var/lib/postgresql/data/
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - internal_net

volumes:
  db_vol: { }

networks:
  internal_net:
    driver: bridge