version: "3.3"

services:
  api:
    container_name: api
    image: nexus.protesys.ru:5000/smartserver:latest
    ports:
      - "9888:9888"
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
      - mongo
    networks:
      - internal_net

  rasp:
    container_name: rasp
    build: .
    restart: unless-stopped
    devices:
      - /dev/gpiomem
    depends_on:
      - api
    networks:
      - internal_net

  db:
    container_name: db
    image: postgres:16.3-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db_vol:/var/lib/postgresql/data/
    networks:
      - internal_net


  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongo_vol:/data/db
    networks:
      - internal_net


volumes:
  db_vol: { }
  mongo_vol: { }

networks:
  internal_net:
    driver: bridge